server:
  port: 8083

api:
  json-place-holder:
    domain: 'jsonplaceholder.typicode.com'
    endpoints:
      users: '/users'
      posts: '/posts'
      albums: '/albums'
  json-gov-hospital:
    domain: 'www.ha.org.hk'
    endpoints:
      data: '/opendata/hosp-bed-en.json'
  weather:
    domain: "data.weather.gov.hk"
    base-paths: "weatherAPI,opendata"
    open-data:
      endpoint: "/opendata.php"